"""Baseline schema: the 11 tables as of multi-user Clerk support.

Autogenerated from the models, then hand-normalized: datetime columns are
timezone-aware (asyncpg refuses naive columns fed tz-aware values; SQLite
ignores the flag) and JSON payload columns become JSONB on Postgres.

Legacy pre-alembic SQLite databases (created by the old create_all +
guarded-ALTER path in app/db.py) already carry exactly this schema —
init_db() stamps them at this revision instead of replaying it.

Revision ID: baseline
Revises: None
Create Date: 2026-08-28

"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "baseline"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# JSONB on Postgres, plain JSON on SQLite — one portable declaration.
_JSON = sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql")


def upgrade() -> None:
    op.create_table(
        "agent_events",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("user_id", sa.String(), nullable=True),
        sa.Column("event_type", sa.String(), nullable=False),
        sa.Column("handler", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("payload", _JSON, nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("agent_events") as batch_op:
        batch_op.create_index(batch_op.f("ix_agent_events_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_agent_events_user_id"), ["user_id"], unique=False)

    op.create_table(
        "agent_memory",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("scope", sa.String(), nullable=False),
        sa.Column("ref_id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("value", _JSON, nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("scope", "ref_id", "key", name="uq_agent_memory_scope_ref_key"),
    )
    with op.batch_alter_table("agent_memory") as batch_op:
        batch_op.create_index(batch_op.f("ix_agent_memory_user_id"), ["user_id"], unique=False)

    op.create_table(
        "modules",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("exam_date", sa.Date(), nullable=True),
        sa.Column("academic_year", sa.String(), nullable=True),
        sa.Column("term", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("modules") as batch_op:
        batch_op.create_index(batch_op.f("ix_modules_user_id"), ["user_id"], unique=False)

    op.create_table(
        "recommendation_events",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("impression_id", sa.String(), nullable=False),
        sa.Column("strategy_name", sa.String(), nullable=False),
        sa.Column("action", sa.String(), nullable=False),
        sa.Column("document_id", sa.String(), nullable=True),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.Column("event_type", sa.String(), nullable=False),
        sa.Column("reward", sa.Float(), nullable=True),
        sa.Column("context_snapshot", _JSON, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("recommendation_events") as batch_op:
        batch_op.create_index(batch_op.f("ix_recommendation_events_impression_id"), ["impression_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_recommendation_events_user_id"), ["user_id"], unique=False)

    op.create_table(
        "user_activities",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("props", _JSON, nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("user_activities") as batch_op:
        batch_op.create_index(batch_op.f("ix_user_activities_ts"), ["ts"], unique=False)
        batch_op.create_index(batch_op.f("ix_user_activities_type"), ["type"], unique=False)
        batch_op.create_index(batch_op.f("ix_user_activities_user_id"), ["user_id"], unique=False)

    op.create_table(
        "lessons",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("module_id", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["module_id"], ["modules.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_table(
        "study_plans",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("module_id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("stale_reasons", _JSON, nullable=False),
        sa.Column("items", _JSON, nullable=False),
        sa.Column("meta", _JSON, nullable=False),
        sa.ForeignKeyConstraint(["module_id"], ["modules.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "module_id", name="uq_study_plans_user_module"),
    )
    with op.batch_alter_table("study_plans") as batch_op:
        batch_op.create_index(batch_op.f("ix_study_plans_module_id"), ["module_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_study_plans_user_id"), ["user_id"], unique=False)

    op.create_table(
        "documents",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("filename", sa.String(), nullable=False),
        sa.Column("mime", sa.String(), nullable=False),
        sa.Column("file_path", sa.String(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("page_count", sa.Integer(), nullable=False),
        sa.Column("char_count", sa.Integer(), nullable=False),
        sa.Column("uploaded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("duration_seconds", sa.Integer(), nullable=True),
        sa.Column("transcription_status", sa.String(), nullable=True),
        sa.Column("transcription_error", sa.Text(), nullable=True),
        sa.Column("lesson_id", sa.String(), nullable=True),
        sa.Column("module_id", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["lesson_id"], ["lessons.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["module_id"], ["modules.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("documents") as batch_op:
        batch_op.create_index(batch_op.f("ix_documents_user_id"), ["user_id"], unique=False)

    op.create_table(
        "content_items",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("document_id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("content", _JSON, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("content_items") as batch_op:
        batch_op.create_index(batch_op.f("ix_content_items_user_id"), ["user_id"], unique=False)

    op.create_table(
        "lecture_sessions",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("lesson_id", sa.String(), nullable=True),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("audio_doc_id", sa.String(), nullable=True),
        sa.Column("slides_doc_id", sa.String(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("duration_seconds", sa.Integer(), nullable=False),
        sa.Column("slide_timestamps", _JSON, nullable=False),
        sa.Column("slide_count", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["audio_doc_id"], ["documents.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["lesson_id"], ["lessons.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["slides_doc_id"], ["documents.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("lecture_sessions") as batch_op:
        batch_op.create_index(batch_op.f("ix_lecture_sessions_user_id"), ["user_id"], unique=False)

    op.create_table(
        "quiz_attempts",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("content_id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("answers", _JSON, nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("correct_count", sa.Integer(), nullable=False),
        sa.Column("total_count", sa.Integer(), nullable=False),
        sa.Column("taken_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["content_id"], ["content_items.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("quiz_attempts") as batch_op:
        batch_op.create_index(batch_op.f("ix_quiz_attempts_user_id"), ["user_id"], unique=False)


def downgrade() -> None:
    op.drop_table("quiz_attempts")
    op.drop_table("lecture_sessions")
    op.drop_table("content_items")
    op.drop_table("documents")
    op.drop_table("study_plans")
    op.drop_table("lessons")
    op.drop_table("user_activities")
    op.drop_table("recommendation_events")
    op.drop_table("modules")
    op.drop_table("agent_memory")
    op.drop_table("agent_events")
