import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useNavigate } from "@tanstack/react-router";
import {
  CalendarDays,
  Sparkles,
  Loader2,
  RefreshCw,
  Check,
  Zap,
  CircleHelp,
  Layers,
  FileText,
  PenLine,
  BrainCircuit,
} from "lucide-react";
import * as api from "../api/client";
import type { PlanItem } from "../api/client";
import { track } from "../api/track";
import type { Module } from "../types";

interface Props {
  module: Module;
}

const ITEM_ICONS: Record<PlanItem["type"], typeof Zap> = {
  review_concepts: BrainCircuit,
  take_quiz: CircleHelp,
  generate_quiz: PenLine,
  review_deck: Layers,
  generate_flashcards: PenLine,
  read_document: FileText,
};

const ITEM_VERBS: Record<PlanItem["type"], string> = {
  review_concepts: "Review",
  take_quiz: "Quiz",
  generate_quiz: "Generate quiz",
  review_deck: "Review deck",
  generate_flashcards: "Generate cards",
  read_document: "Read",
};

/**
 * Clean a planner rationale for display: the planner sometimes echoes its
 * internal grounding flags ("(has_quiz: false, has_deck: false)") or
 * rambles about them, which reads like debug output. Strip those
 * fragments and tidy punctuation; if the text still looks like leaked
 * grounding (unfixable), drop it — the item title carries the meaning.
 */
function cleanRationale(text: string): string {
  const cleaned = text
    .replace(/\s*\(?has_(?:quiz|deck|notes):\s*(?:true|false)\)?/gi, "")
    .replace(/\(\s*\)/g, "")
    .replace(/,\s*\.|,\s*,/g, ".")
    .replace(/\s{2,}/g, " ")
    .trim();
  if (/has_(?:quiz|deck|notes)/i.test(cleaned) || cleaned.length < 10) {
    return "";
  }
  return cleaned;
}

/**
 * The module's adaptive study plan. Generated by the agent from the module's
 * documents, concept mastery + FSRS schedule, and the learner profile;
 * paced toward the exam date; regenerated in the background when new
 * content lands. Items deep-link to module-scoped actions and are marked
 * done automatically from real study events.
 */
export function ModulePlanPanel({ module }: Props) {
  const navigate = useNavigate();
  const queryClient = useQueryClient();
  const [planning, setPlanning] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [editingDate, setEditingDate] = useState(false);

  const plan = useQuery({
    queryKey: ["study-plan", module.id],
    queryFn: () => api.getStudyPlan(module.id),
    refetchInterval: 30000, // background regens surface without a refresh
  });

  const toggleItem = useMutation({
    mutationFn: ({
      itemId,
      status,
    }: {
      itemId: string;
      status: "done" | "pending";
    }) => api.patchPlanItem(plan.data!.id, itemId, status),
    onSuccess: () =>
      queryClient.invalidateQueries({ queryKey: ["study-plan", module.id] }),
  });

  async function handleGenerate(examDate?: string | null) {
    setPlanning(true);
    setError(null);
    track("plan.generated", { module_id: module.id });
    try {
      await api.generateStudyPlan(module.id, examDate);
      await queryClient.invalidateQueries({ queryKey: ["study-plan", module.id] });
      await queryClient.invalidateQueries({ queryKey: ["module-tree"] });
    } catch (e) {
      setError((e as Error).message);
    } finally {
      setPlanning(false);
    }
  }

  const data = plan.data;
  const daysToExam = module.exam_date
    ? Math.ceil(
        (new Date(module.exam_date + "T00:00:00").getTime() - Date.now()) / 86400000,
      )
    : null;

  // ---- Empty state: invite + exam-date picker -----------------------------
  if (!data && !planning) {
    return (
      <div className="module-plan module-plan-empty">
        <div className="module-plan-empty-text">
          <div className="module-plan-empty-title">
            <Sparkles size={15} />
            Study plan
          </div>
          <p>
            The agent can plan this module — paced toward your exam, adapting
            as lectures are added.
          </p>
        </div>
        <div className="module-plan-empty-actions">
          <input
            type="date"
            className="module-plan-date-input"
            aria-label="Exam date (optional)"
            onChange={(e) => {
              if (e.target.value) void handleGenerate(e.target.value);
            }}
          />
          <button className="primary" onClick={() => handleGenerate()}>
            <Sparkles size={14} />
            Plan this module
          </button>
        </div>
      </div>
    );
  }

  if (planning || (plan.isLoading && !data)) {
    return (
      <div className="module-plan module-plan-planning">
        <Loader2 size={18} className="spinner" />
        <span>
          The agent is planning this module — reading your documents, mastery,
          and due concepts…
        </span>
      </div>
    );
  }

  if (!data) return null;

  // ---- Plan view ------------------------------------------------------------
  const items = data.items ?? [];
  const done = items.filter((i) => i.status === "done").length;
  const progressPct = items.length ? Math.round((done / items.length) * 100) : 0;

  // Group items by day offset.
  const groups = new Map<number, PlanItem[]>();
  for (const item of items) {
    const k = item.day_offset;
    if (!groups.has(k)) groups.set(k, []);
    groups.get(k)!.push(item);
  }

  function openItem(item: PlanItem) {
    track("plan.item_opened", {
      module_id: module.id,
      item_type: item.type,
      document_id: item.target.document_id ?? null,
    });
    const docId = item.target.document_id;
    if (item.type === "review_concepts") {
      navigate({ to: "/study", search: { module: module.id } });
    } else if (docId) {
      const tab =
        item.type === "take_quiz" || item.type === "generate_quiz"
          ? "quiz"
          : item.type === "review_deck" || item.type === "generate_flashcards"
            ? "flashcards"
            : "document";
      navigate({
        to: "/documents/$docId/$tab",
        params: { docId, tab },
      });
    }
  }

  return (
    <div className="module-plan">
      <div className="module-plan-header">
        <div className="module-plan-title">
          <CalendarDays size={15} />
          <span>Study plan</span>
          {daysToExam !== null && (
            <span
              className={`module-plan-exam-chip ${daysToExam <= 7 ? "soon" : ""}`}
            >
              exam in {daysToExam} day{daysToExam === 1 ? "" : "s"}
            </span>
          )}
          {editingDate ? (
            <input
              type="date"
              className="module-plan-date-input"
              defaultValue={module.exam_date ?? ""}
              autoFocus
              onChange={async (e) => {
                setEditingDate(false);
                if (e.target.value && e.target.value !== module.exam_date) {
                  await api.setModuleExamDate(module.id, e.target.value);
                  await queryClient.invalidateQueries({ queryKey: ["module-tree"] });
                }
              }}
              onBlur={() => setEditingDate(false)}
            />
          ) : (
            <button
              type="button"
              className="module-plan-date-edit"
              onClick={() => setEditingDate(true)}
              title={module.exam_date ? "Change exam date" : "Set exam date"}
            >
              {module.exam_date ?? "set exam date"}
            </button>
          )}
        </div>
        <div className="module-plan-meta">
          <span className="module-plan-progress">
            {done}/{items.length} done · {progressPct}%
          </span>
          <span className="module-plan-generated">
            v{data.version} · {timeAgo(data.generated_at)}
            {data.staleness?.stale && (
              <em className="module-plan-stale">
                {" "}· {data.staleness.reasons[0]}
              </em>
            )}
          </span>
          <button
            type="button"
            className="module-plan-refresh"
            disabled={planning}
            onClick={() => handleGenerate()}
            title="Regenerate the plan from current module state"
          >
            {planning ? (
              <Loader2 size={13} className="spinner" />
            ) : (
              <RefreshCw size={13} />
            )}
          </button>
        </div>
      </div>

      <div className="module-plan-progress-bar">
        <div className="module-plan-progress-fill" style={{ width: `${progressPct}%` }} />
      </div>

      {error && <div className="error">{error}</div>}

      <div className="module-plan-days">
        {[...groups.entries()].map(([offset, dayItems]) => (
          <div key={offset} className="module-plan-day">
            <div className="module-plan-day-label">{dayLabel(offset)}</div>
            <div className="module-plan-day-items">
              {dayItems.map((item) => {
                const Icon = ITEM_ICONS[item.type] ?? Zap;
                const isDone = item.status === "done";
                return (
                  <div
                    key={item.id}
                    className={`module-plan-item ${isDone ? "done" : ""}`}
                  >
                    <button
                      type="button"
                      className="module-plan-item-main"
                      onClick={() => !isDone && openItem(item)}
                    >
                      <span className="module-plan-item-icon">
                        <Icon size={14} />
                      </span>
                      <span className="module-plan-item-text">
                        <span className="module-plan-item-title">
                          {ITEM_VERBS[item.type]}: {item.title}
                        </span>
                        {item.rationale && (
                          <span className="module-plan-item-rationale">
                            {isDone && item.done_reason
                              ? `✓ ${item.done_reason}`
                              : cleanRationale(item.rationale)}
                          </span>
                        )}
                      </span>
                      <span className="module-plan-item-est">
                        {item.estimate_mins}m
                      </span>
                    </button>
                    <button
                      type="button"
                      className={`module-plan-check ${isDone ? "on" : ""}`}
                      title={isDone ? (item.done_kind === "auto" ? "Done (detected automatically)" : "Mark as not done") : "Mark done"}
                      onClick={() =>
                        toggleItem.mutate({
                          itemId: item.id,
                          status: isDone ? "pending" : "done",
                        })
                      }
                    >
                      <Check size={13} />
                    </button>
                  </div>
                );
              })}
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}

function dayLabel(offset: number): string {
  if (offset === 0) return "Today";
  if (offset === 1) return "Tomorrow";
  const d = new Date();
  d.setDate(d.getDate() + offset);
  return d.toLocaleDateString(undefined, { weekday: "short", day: "numeric", month: "short" });
}

function timeAgo(iso: string): string {
  const mins = Math.floor((Date.now() - new Date(iso).getTime()) / 60000);
  if (mins < 1) return "just now";
  if (mins < 60) return `${mins}m ago`;
  const hours = Math.floor(mins / 60);
  if (hours < 24) return `${hours}h ago`;
  return `${Math.floor(hours / 24)}d ago`;
}
